#!/usr/bin/env python3
"""Verify required files, hashes, notebook execution and smoke-test outputs."""

from __future__ import annotations

import json
import sys
from pathlib import Path

import nbformat
import pandas as pd


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from rogii_portfolio.artifacts import sha256_file, verify_manifest, write_json  # noqa: E402


REQUIRED = (
    "README.md",
    "KAGGLE_UPLOAD.md",
    "portfolio_notebook.ipynb",
    "portfolio_notebook_executed.ipynb",
    "evidence/manifest.json",
    "evidence/math_render_qa.json",
    "evidence/source_manifest.json",
    "evidence/curated_evidence_manifest.json",
    "evidence/portfolio_notebook_rendered.html",
    "evidence/deployment_smoke_submission.csv",
    "evidence/deployment_smoke_audit.json",
    "src/rogii_portfolio/particle.py",
    "src/rogii_portfolio/geohmm.py",
    "src/rogii_portfolio/hgrg.py",
    "src/rogii_portfolio/meta_state.py",
    "src/rogii_portfolio/switching_state.py",
    "src/rogii_portfolio/group_robust.py",
    "src/rogii_portfolio/trust_region.py",
    "src/rogii_portfolio/evaluation.py",
    "src/rogii_portfolio/overlays.py",
    "src/rogii_portfolio/features.py",
    "src/rogii_portfolio/historical_features.py",
    "src/rogii_portfolio/deployment.py",
    "src/rogii_portfolio/parents.py",
    "src/rogii_portfolio/regret_router.py",
    "src/rogii_portfolio/stack.py",
    "src/rogii_portfolio/pipeline.py",
    "configs/smoke.json",
    "configs/full.json",
    "configs/realdata_nested_160.json",
    "configs/realdata_nested_160_confirmation.json",
    "configs/realdata_switching_160.json",
    "configs/robustness_registry.json",
    "docs/METHODOLOGY_REVIEW.md",
    "docs/ROBUSTNESS_EVALUATION.md",
    "requirements.txt",
    "environment.yml",
    "LICENSE",
    "Makefile",
)


CURATED_EVIDENCE = (
    "evidence/historical_stage_scores.csv",
    "evidence/method_lineage.json",
    "evidence/optimizer_v1b_selected_recipes.csv",
    "evidence/optimizer_v1b_full_summary.json",
    "evidence/optimizer_v1b_fold_metrics.csv",
)


SOURCE_PATTERNS = (
    ".gitignore",
    "README.md",
    "KAGGLE_UPLOAD.md",
    "LICENSE",
    "Makefile",
    "requirements.txt",
    "environment.yml",
    "pyproject.toml",
    "reproduce.py",
    "portfolio_notebook.ipynb",
    "configs/*.json",
    "docs/*.md",
    "scripts/*.py",
    "src/**/*.py",
    "tests/*.py",
)


def write_source_manifest() -> dict:
    """Hash every reproducibility input, independently of generated evidence."""

    (ROOT / "evidence").mkdir(parents=True, exist_ok=True)
    paths = sorted(
        {
            path
            for pattern in SOURCE_PATTERNS
            for path in ROOT.glob(pattern)
            if path.is_file()
        },
        key=lambda path: path.as_posix(),
    )
    payload = {
        "schema": "rogii_portfolio_source_manifest_v1",
        "files": [
            {
                "path": path.relative_to(ROOT).as_posix(),
                "bytes": path.stat().st_size,
                "sha256": sha256_file(path),
            }
            for path in paths
        ],
    }
    write_json(ROOT / "evidence" / "source_manifest.json", payload)
    return payload


def write_curated_evidence_manifest() -> dict:
    """Hash fixed evidence that is displayed but not regenerated by smoke CV."""

    missing = [name for name in CURATED_EVIDENCE if not (ROOT / name).is_file()]
    if missing:
        raise RuntimeError(f"curated evidence is incomplete: {missing}")
    payload = {
        "schema": "rogii_portfolio_curated_evidence_manifest_v1",
        "files": [
            {
                "path": name,
                "bytes": (ROOT / name).stat().st_size,
                "sha256": sha256_file(ROOT / name),
            }
            for name in CURATED_EVIDENCE
        ],
    }
    write_json(ROOT / "evidence" / "curated_evidence_manifest.json", payload)
    return payload


def main() -> int:
    source_manifest = write_source_manifest()
    curated_manifest = write_curated_evidence_manifest()
    missing = [name for name in REQUIRED if not (ROOT / name).exists()]
    if missing:
        raise RuntimeError(f"portfolio is incomplete: {missing}")
    manifest = verify_manifest(ROOT)
    notebook = nbformat.read(ROOT / "portfolio_notebook_executed.ipynb", as_version=4)
    errors = [
        output
        for cell in notebook.cells
        if cell.cell_type == "code"
        for output in cell.get("outputs", [])
        if output.get("output_type") == "error"
    ]
    if errors:
        raise RuntimeError(f"executed notebook contains {len(errors)} errors")
    counts = [cell.get("execution_count") for cell in notebook.cells if cell.cell_type == "code"]
    if not counts or any(value is None for value in counts):
        raise RuntimeError("not every code cell was executed")
    math_qa = json.loads((ROOT / "evidence" / "math_render_qa.json").read_text(encoding="utf-8"))
    if math_qa.get("status") != "PASS" or math_qa.get("display_formulas", 0) < 8:
        raise RuntimeError("math render QA did not pass")
    deployment = json.loads(
        (ROOT / "evidence" / "deployment_smoke_audit.json").read_text(encoding="utf-8")
    )
    deployment_csv = ROOT / "evidence" / "deployment_smoke_submission.csv"
    if (
        deployment.get("status") != "PASS"
        or deployment.get("targets_contained_tvt") is not False
        or deployment.get("csv_sha256") != sha256_file(deployment_csv)
    ):
        raise RuntimeError("deployment smoke audit did not pass")
    exact = json.loads((ROOT / "configs" / "exact_artifacts.json").read_text(encoding="utf-8"))
    local_checks = []
    for item in exact["local_lineage"]:
        path = (ROOT / item["path"]).resolve()
        local_checks.append(
            {
                "path": str(path),
                "exists": path.exists(),
                "sha256_matches": path.exists() and sha256_file(path) == item["sha256"],
            }
        )
    mismatched_lineage = [item["path"] for item in local_checks if item["exists"] and not item["sha256_matches"]]
    if mismatched_lineage:
        raise RuntimeError(f"local historical lineage changed: {mismatched_lineage}")
    external_checks = []
    for item in exact["external_required"]:
        local_path = item.get("local_path")
        expected_sha = item.get("pinned_version_sha256")
        path = (ROOT / local_path).resolve() if local_path else None
        exists = bool(path is not None and path.is_file())
        matches = bool(exists and expected_sha and sha256_file(path) == expected_sha)
        external_checks.append(
            {
                "kaggle_dataset": item["kaggle_dataset"],
                "local_path": None if path is None else str(path),
                "exists": exists,
                "sha256_matches": matches,
            }
        )
    nested_roots = [
        ROOT / "artifacts" / "realdata_nested_160",
        ROOT / "artifacts" / "realdata_nested_160_confirmation",
    ]
    official_nested_checks = []
    for nested_root in nested_roots:
        if not (nested_root / "evidence" / "manifest.json").exists():
            official_nested_checks.append({"root": str(nested_root), "exists": False, "verified": False})
            continue
        verify_manifest(nested_root)
        nested_summary = json.loads(
            (nested_root / "evidence" / "reproduction_summary.json").read_text(encoding="utf-8")
        )
        verified = bool(
            nested_summary.get("mode") == "full"
            and nested_summary.get("component_graph_scope_wells") == 320
            and nested_summary.get("target_isolation", {}).get("component_overlap_count") == 0
            and nested_summary.get("target_isolation", {}).get("suffix_truth_in_prediction_api") is False
        )
        official_nested_checks.append(
            {
                "root": str(nested_root),
                "exists": True,
                "verified": verified,
                "wells": nested_summary.get("wells"),
                "components": nested_summary.get("components"),
            }
        )
    disjoint_panels = False
    if all(item["verified"] for item in official_nested_checks):
        primary = json.loads(
            (nested_roots[0] / "evidence" / "reproduction_summary.json").read_text(encoding="utf-8")
        )
        confirmation = json.loads(
            (nested_roots[1] / "evidence" / "reproduction_summary.json").read_text(encoding="utf-8")
        )
        primary_table = pd.read_csv(nested_roots[0] / "evidence" / "geological_components.csv")
        confirmation_table = pd.read_csv(
            nested_roots[1] / "evidence" / "geological_components.csv"
        )
        disjoint_panels = not bool(
            set(primary_table["component"].astype(str))
            & set(confirmation_table["component"].astype(str))
        ) and primary["wells"] + confirmation["wells"] == 320

    robustness_root = ROOT / "artifacts" / "robustness_evaluation"
    robustness_manifest_path = robustness_root / "manifest.json"
    robustness_verified = False
    if robustness_manifest_path.exists():
        robustness_manifest = json.loads(robustness_manifest_path.read_text(encoding="utf-8"))
        robustness_verified = all(
            (robustness_root / item["path"]).is_file()
            and sha256_file(robustness_root / item["path"]) == item["sha256"]
            for item in robustness_manifest.get("artifacts", [])
        )
        robustness_summary = json.loads(
            (robustness_root / "summary.json").read_text(encoding="utf-8")
        )
        robustness_verified = bool(
            robustness_verified
            and robustness_manifest.get("schema") == "rogii_robustness_evaluation_manifest_v1"
            and robustness_summary.get("quality_checks") == {"failed": 0, "passed": 85}
        )
    report = {
        "status": "PASS",
        "manifest_artifacts": len(manifest["artifacts"]),
        "source_files": len(source_manifest["files"]),
        "curated_evidence_files": len(curated_manifest["files"]),
        "notebook_code_cells": len(counts),
        "notebook_all_cells_executed": True,
        "math_render_qa": math_qa,
        "deployment_smoke": deployment,
        "local_lineage": local_checks,
        "external_artifacts": external_checks,
        "exact_byte_reproduction_ready": bool(external_checks) and all(
            item["sha256_matches"] for item in external_checks
        ),
        "smoke_algorithmic_reproduction_ready": True,
        "official_nested_panels": official_nested_checks,
        "official_nested_320_verified": bool(
            all(item["verified"] for item in official_nested_checks) and disjoint_panels
        ),
        "official_expensive_full_profile_verified_in_this_run": False,
        "robustness_registry_verified": robustness_verified,
    }
    (ROOT / "evidence" / "verification_report.json").write_text(
        json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    print(json.dumps(report, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
